<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>toml_to_object.tests</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="TUnit" Version="1.65.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\toml-to-object\toml-to-object.csproj" />
    </ItemGroup>

</Project>
